  
language: swift
osx_image: xcode12.2
xcode_project: r2-testapp-swift.xcodeproj
xcode_scheme: 'r2-testapp-swift (carthage)'
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_sdk: iphonesimulator13.0

branches:
  only:
    - master
    - develop

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --use-xcframeworks --platform iOS --cache-builds

script:
  - xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -quiet

